### ISSUE TITLE
License

### ISSUE THREAD

**Issue by stfsy** [ahmedbesbes/multi-label-sentiment-classifier#1]
hi @ahmedbesbes great story on Medium! Than you very much!

Could you add a License to your code? I'd be interested in using some parts of it.

**Comment by ahmedbesbes** [comment]
Hello @stfsy 
Thank you for your feedback
The project is licenced under MIT Licence.
Enjoy!

**Comment by stfsy** [comment]
@ahmedbesbes you're awesome!! thank you very much
